---

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true

jobs:
  ###########################
  #  BUILD & PUBLISH STAGE
  ###########################
  test-kotlin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: cache
        uses: actions/cache@v3
        with:
          key: kotlin-build
          path: .gradle
      - name: Publish to Nexus and to GitLab with Gradle Wrapper
        env:
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
          GITLAB_PACKAGES_UPLOAD_TOKEN: ${{ secrets.GITLAB_PACKAGES_UPLOAD_TOKEN }}
          VERSION: ${{ github.event.inputs.version }}
          TAG_NAME: gooddata-server-oauth2-${{ github.event.inputs.version }}
        run: |
          echo ">>> git tag $TAG_NAME" |
          echo ">>> git push origin $TAG_NAME"
          echo ">>> ./gradlew clean publish -Pversion=$TAG_NAME --info"

